# This file is part of the YesWiki Extension alternativeupdatej9rem.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  alternative_yeswiki_repository: # auj9-autoupdate-system
    J9rem: "https://repo-yw.j9rem.net/"
  activateEventRepetition: false # Feature UUID : auj9-recurrent-events
  eventRepetitionTriggerErrorsForAdmins: false # Feature UUID : auj9-recurrent-events
  canDuplicateEntryIfNotRightToWrite: false # Feature UUID : auj9-duplicate
  sendMail:
    activated: false            # Feature UUID : auj9-bazar-list-send-mail-dynamic
  formIdAreaToDepartment: ''    # Feature UUID : auj9-autoupdateareas-action
  updatablePackagesViaAlternative: # Feature UUID : auj9-autoupdate-system
    - 'advancedsearch'
    - 'nextcloudconnector'
    - 'stats'
    - 'twolevels'
  localCache:                   # Feature UUID : auj9-local-cache
    activated: false
    limitedGroups: # coma separated
  cleanUnusedMetadata: false    # auj9-fix-edit-metadata
  default-sender-email: ''      # Feature UUID : auj9-bazar-list-send-mail-dynamic
  deletePagesAndEntriesWithUser: false # Feature UUID : auj9-feat-user-controller-delete-own-pages
  openAgenda: # Feature UUID : auj9-open-agenda-connect
    isActivated: false
    privateApiKeys: null
    associations: null
  sortListAsDefinedInFilters: false # Feature UUID : auj9-bazarlist-filter-order
  authorizedGroupToForceEntrySaving: admins # Feature UUID : auj9-can-force-entry-save-for-specific-group
  showLinkToContentPageIfExisting: true     # Feature UUID : auj9-can-choose-to-hide-link-to-content-page
  editEntryInsteadOfShowingIfOnlyOne: false # Feature UUID : auj9-option-entrycontroller-edit-instead-of-view-if-only-one
  sqlConnectTimeout: 0                      # Feature UUID : auj9-perf-sql
  displayedFormsInRssHandler:               # Feature UUID : auj9-perf-sql
  alternativeupdatej9rem_editable_config_params:
    - 'activateEventRepetition' # Feature UUID : auj9-recurrent-events
    - 'eventRepetitionTriggerErrorsForAdmins' # Feature UUID : auj9-recurrent-events
    - 'canDuplicateEntryIfNotRightToWrite' # Feature UUID : auj9-duplicate
    - localCache:               # Feature UUID : auj9-local-cache
      - 'activated'
      - 'limitedGroups'
    - 'cleanUnusedMetadata'     # auj9-fix-edit-metadata
    - sendMail:                 # Feature UUID : auj9-bazar-list-send-mail-dynamic
      - 'activated'
    - 'formIdAreaToDepartment'  # Feature UUID : auj9-autoupdateareas-action
    - 'default-sender-email'    # Feature UUID : auj9-bazar-list-send-mail-dynamic
    - 'deletePagesAndEntriesWithUser' # Feature UUID : auj9-feat-user-controller-delete-own-pages
    - openAgenda: # Feature UUID : auj9-open-agenda-connect
      - isActivated
    - 'sortListAsDefinedInFilters' # Feature UUID : auj9-bazarlist-filter-order
    - 'authorizedGroupToForceEntrySaving'  # Feature UUID : auj9-can-force-entry-save-for-specific-group
    - 'showLinkToContentPageIfExisting'    # Feature UUID : auj9-can-choose-to-hide-link-to-content-page
    - 'editEntryInsteadOfShowingIfOnlyOne' # Feature UUID : auj9-option-entrycontroller-edit-instead-of-view-if-only-one
    - 'sqlConnectTimeout'                  # Feature UUID : auj9-perf-sql
    - 'displayedFormsInRssHandler'         # Feature UUID : auj9-perf-sql

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Alternativeupdatej9rem\Service\:
    resource: 'services/*'
  YesWiki\Alternativeupdatej9rem\Controller\:
    resource: 'controllers/*'
  # Feature UUID : auj9-fix-edit-metadata
  # Feature UUID : auj9-fix-4-4-3
  # Feature UUID : auj9-can-force-entry-save-for-specific-group 
  YesWiki\Alternativeupdatej9rem\Service\PageManager:
    decorates: YesWiki\Core\Service\PageManager
    decoration_on_invalid: null
  # Feature UUID : auj9-custom-changes
  YesWiki\Alternativeupdatej9rem\Service\FieldFactory:
    decorates: YesWiki\Bazar\Service\FieldFactory
    decoration_on_invalid: null
  # Feature UUID : auj9-can-force-entry-save-for-specific-group
  YesWiki\Alternativeupdatej9rem\Service\AssetsManager:
    decorates: YesWiki\Core\Service\AssetsManager
    decoration_on_invalid: null
  # Feature UUID : auj9-bazarlist-filter-order
  YesWiki\Alternativeupdatej9rem\Service\BazarListService:
    decorates: YesWiki\Bazar\Service\BazarListService
    decoration_on_invalid: null
  # Feature UUID : auj9-fix-4-4-3
  YesWiki\Alternativeupdatej9rem\Service\FormManager:
    decorates: YesWiki\Bazar\Service\FormManager
    decoration_on_invalid: null
  # Feature UUID : auj9-perf-sql
  YesWiki\Alternativeupdatej9rem\Service\DbService:
    decorates: YesWiki\Core\Service\DbService
    decoration_on_invalid: null
  YesWiki\Alternativeupdatej9rem\Service\Performer:
    decorates: YesWiki\Core\Service\Performer
    decoration_on_invalid: null
  # Feature UUID : auj9-option-entrycontroller-edit-instead-of-view-if-only-one
  YesWiki\Alternativeupdatej9rem\Controller\EntryController:
    decorates: YesWiki\Bazar\Controller\EntryController
    decoration_on_invalid: null
  # Feature UUID : auj9-fix-4-4-2
  YesWiki\Alternativeupdatej9rem\Controller\IcalFormatter:
    decorates: YesWiki\Bazar\Controller\IcalFormatter
    decoration_on_invalid: null
  # Feature UUID : auj9-fix-4-4-3 maybe needed 4.4.4
  YesWiki\Alternativeupdatej9rem\Controller\SecurityController:
    decorates: YesWiki\Security\Controller\SecurityController
    decoration_on_invalid: null
  # Feature UUID : auj9-feat-user-controller-delete-own-pages
  YesWiki\Alternativeupdatej9rem\Controller\UserController:
    decorates: YesWiki\Core\Controller\UserController
    decoration_on_invalid: null
  # Feature UUID : auj9-video-field
  # Feature UUID : auj9-bazar-list-video-dynamic
  YesWiki\Alternativeupdatej9rem\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'
  # Feature UUID : auj9-recurrent-events
  YesWiki\Alternativeupdatej9rem\Service\DateService:
    tags:
      - { name: yeswiki.event_subscriber }
  # Feature UUID : auj9-duplicate
  YesWiki\Alternativeupdatej9rem\Service\DuplicationFollower:
    tags:
      - { name: yeswiki.event_subscriber }
  # Feature UUID : auj9-local-cache
  YesWiki\Alternativeupdatej9rem\Service\CacheService:
    tags:
      - { name: yeswiki.event_subscriber }
  # Feature UUID : auj9-open-agenda-connect
  YesWiki\Alternativeupdatej9rem\Service\ConfigOpenAgendaService:
    tags:
      - { name: yeswiki.event_subscriber }
  # Feature UUID : auj9-subscribe-to-entry
  YesWiki\Alternativeupdatej9rem\Service\SubscriptionManager:
    tags:
      - { name: yeswiki.event_subscriber }