# This file is part of the YesWiki Extension alternativeupdatej9rem.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  alternative_yeswiki_repository: # auj9-autoupdate-system
    J9rem: "https://repository.oui-wiki.pro/"
  activateEventRepetition: false # Feature UUID : auj9-recurrent-events
  canDuplicateEntryIfNotRightToWrite: false # Feature UUID : auj9-duplicate
  sendMail:
    activated: false            # Feature UUID : auj9-bazar-list-send-mail-dynamic
  formIdAreaToDepartment: ''    # Feature UUID : auj9-autoupdateareas-action
  updatablePackagesViaAlternative: # Feature UUID : auj9-autoupdate-system
    - 'advancedsearch'
    - 'nextcloudconnector'
    - 'stats'
    - 'twolevels'
  localCache:                   # Feature UUID : auj9-local-cache
    activated: false
    limitedGroups: # coma separated
  cleanUnusedMetadata: false    # auj9-fix-edit-metadata
  default-sender-email: ''      # Feature UUID : auj9-bazar-list-send-mail-dynamic
  alternativeupdatej9rem_editable_config_params:
    - 'activateEventRepetition' # Feature UUID : auj9-recurrent-events
    - 'canDuplicateEntryIfNotRightToWrite' # Feature UUID : auj9-duplicate
    - localCache:               # Feature UUID : auj9-local-cache
      - 'activated'
      - 'limitedGroups'
    - 'cleanUnusedMetadata'     # auj9-fix-edit-metadata
    - sendMail:                 # Feature UUID : auj9-bazar-list-send-mail-dynamic
      - 'activated'
    - 'formIdAreaToDepartment'  # Feature UUID : auj9-autoupdateareas-action
    - 'default-sender-email'    # Feature UUID : auj9-bazar-list-send-mail-dynamic

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Alternativeupdatej9rem\Service\:
    resource: 'services/*'
  YesWiki\Alternativeupdatej9rem\Controller\:
    resource: 'controllers/*'
  # Feature UUID : auj9-fix-edit-metadata
  YesWiki\Alternativeupdatej9rem\Service\PageManager:
    decorates: YesWiki\Core\Service\PageManager
    decoration_on_invalid: null
  # Feature UUID : auj9-custom-changes
  YesWiki\Alternativeupdatej9rem\Service\FieldFactory:
    decorates: YesWiki\Bazar\Service\FieldFactory
    decoration_on_invalid: null
  # Feature UUID : auj9-fix-4-4-2
  YesWiki\Alternativeupdatej9rem\Controller\IcalFormatter:
    decorates: YesWiki\Bazar\Controller\IcalFormatter
    decoration_on_invalid: null
  # Feature UUID : auj9-video-field
  # Feature UUID : auj9-bazar-list-video-dynamic
  YesWiki\Alternativeupdatej9rem\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'
  # Feature UUID : auj9-recurrent-events
  YesWiki\Alternativeupdatej9rem\Service\DateService:
    tags:
      - { name: yeswiki.event_subscriber }
  # Feature UUID : auj9-duplicate
  YesWiki\Alternativeupdatej9rem\Service\DuplicationFollower:
    tags:
      - { name: yeswiki.event_subscriber }
  # Feature UUID : auj9-local-cache
  YesWiki\Alternativeupdatej9rem\Service\CacheService:
    tags:
      - { name: yeswiki.event_subscriber }